### ISSUE TITLE
Token authentication?

### ISSUE THREAD

**Issue by m00nwtchr** [jellyfin/mopidy-jellyfin#125]
I'd like to be able to log in via a token instead of a password, so that I don't have to store it on disk in plaintext.

Let me know if I can PR this feature etc.

**Comment by mcarlton00** [comment]
For some reason I thought that was already supported, but I was thinking of user_id instead.  I'm not opposed to it, especially if you're wanting to work on it.  The one caveat is that we should include documentation or a method to generate an auth token since most users won't be familiar how to do that.

**Comment by ptwales** [comment]
> The one caveat is that we should include documentation or a method to generate an auth token since most users won't be familiar how to do that.

This was not done.  All I've found for documentation is:
1.  [this gist](https://gist.github.com/nielsvanvelzen/ea047d9028f676185832e51ffaf12a6f)  which states access tokens are not API keys.
2. [this blogpost](https://jmshrv.com/posts/jellyfin-api/) says access tokens are generated after authentication
3. [jellyfin-kotlin-sdk](https://kotlin-sdk.jellyfin.org/guide/authentication.html) says the same thing.

I've tried curling the the [AuthenticateUserByName](https://api.jellyfin.org/#tag/User/operation/AuthenticateUserByName) but it gives me 401 Unauthorized.  Am I also supposed to put my username and password in a header too?  Or generate an API key just to generate a token?
