### ISSUE TITLE
import multiple jellyfin servers

### ISSUE THREAD

**Issue by k1llerk3ks** [jellyfin/mopidy-jellyfin#132]
I am missing the function to include multiple instances of jellyfin. Is this somehow possible without having to run more than one mopidy instance? Thanks!

**Comment by mcarlton00** [comment]
There's really no way to do this within the client currently, and implementing it would be no small feat (plus probably slow down processing speed significantly).  In theory you could install multiple local versions and change what config file heading it looks for (ie, instead of looking for `[jellyfin]` it could look for `[jellyfin2]`), but that's a bit outside of normal operation.  I suspect there would be several other minor changes that would have to happen, but I don't know what those would be off the top of my head.
